export const dummyBuses = [
  {
    id: 1,
    name: "RedBus Express",
    type: "Sleeper (2+1)",
    departureTime: "06:00 AM",
    arrivalTime: "02:00 PM",
    duration: "8h 00m",
    price: 850,
    seatsAvailable: 12,
    isAC: true,
    category: "morning",
    rating: 4.5,
    route: { from: "Delhi", to: "Jaipur" }
  },
  {
    id: 2,
    name: "Intercity SmartBus",
    type: "Semi Sleeper AC",
    departureTime: "09:30 AM",
    arrivalTime: "05:30 PM",
    duration: "8h 00m",
    price: 1200,
    seatsAvailable: 5,
    isAC: true,
    category: "morning",
    rating: 4.8,
    route: { from: "Mumbai", to: "Pune" }
  },
  {
    id: 3,
    name: "Greenline Travels",
    type: "Non-AC Seater",
    departureTime: "02:00 PM",
    arrivalTime: "10:00 PM",
    duration: "8h 00m",
    price: 550,
    seatsAvailable: 24,
    isAC: false,
    category: "afternoon",
    rating: 4.0,
    route: { from: "Delhi", to: "Chandigarh" }
  },
  {
    id: 4,
    name: "Night Owl Travels",
    type: "AC Sleeper (2+1)",
    departureTime: "10:30 PM",
    arrivalTime: "06:30 AM",
    duration: "8h 00m",
    price: 1500,
    seatsAvailable: 8,
    isAC: true,
    category: "evening",
    rating: 4.9,
    route: { from: "Hyderabad", to: "Bangalore" }
  },
  {
    id: 5,
    name: "VRL Travels",
    type: "Multi-Axle AC Sleeper",
    departureTime: "08:15 PM",
    arrivalTime: "04:15 AM",
    duration: "8h 00m",
    price: 1800,
    seatsAvailable: 2,
    isAC: true,
    category: "evening",
    rating: 4.7,
    route: { from: "Bangalore", to: "Chennai" }
  },
  {
    id: 6,
    name: "KSRTC Ambaari",
    type: "Club Class AC",
    departureTime: "11:00 AM",
    arrivalTime: "07:00 PM",
    duration: "8h 00m",
    price: 1100,
    seatsAvailable: 15,
    isAC: true,
    category: "morning",
    rating: 4.6,
    route: { from: "Bangalore", to: "Mysore" }
  }
];
